backend:
  name: git-gateway
  branch: main
media_folder: public/images/uploads
public_folder: images/uploads
publish_mode: editorial_workflow
collections:
  - name: 'posts'
    label: 'Posts'
    label_singular: 'Post'
    folder: '_content/posts'
    create: true
    delete: false
    preview_path: 'learn/{{fields.category}}/{{slug}}'
    fields:
      - name: 'title'
        label: 'Title'
        widget: 'string'
      - name: 'published_at'
        label: 'Published At'
        widget: 'datetime'
        format: 'YYYY-MM-DD-HH-mm'
        date_format: 'dddd, MMMM D, YYYY'
        time_format: 'h:mm a'
      - name: 'category'
        label: 'Category'
        widget: 'relation'
        collection: 'categories'
        search_fields: ['title', 'slug']
        value_field: '{{slug}}'
        display_fields: ['title', 'slug']
      - name: 'tags'
        label: 'Tags'
        widget: 'relation'
        collection: 'tags'
        multiple: true
        search_fields: ['title', 'slug']
        value_field: '{{slug}}'
        display_fields: ['title', 'slug']
      - name: 'thumbnail'
        label: 'Featured Image'
        widget: 'image'
        allow_multiple: false
        media_folder: '/public/images/posts/{{slug}}'
      - name: 'excerpt'
        label: 'Excerpt'
        widget: 'text'
      - name: 'body'
        label: 'Body'
        widget: 'markdown'
  - name: 'categories'
    label: 'Categories'
    label_singular: 'Category'
    folder: '_content/categories'
    create: true
    delete: false
    preview_path: 'learn/{{slug}}'
    fields:
      - name: 'title'
        label: 'Name'
        widget: 'string'
      - name: 'body'
        label: 'Body'
        widget: 'markdown'
  - name: 'tags'
    label: 'Tags'
    label_singular: 'Tag'
    folder: '_content/tags'
    create: true
    delete: false
    preview_path: 'learn/tags/{{slug}}'
    fields:
      - name: 'title'
        label: 'Name'
        widget: 'string'
      - name: 'body'
        label: 'Body'
        widget: 'markdown'
  - name: 'projects'
    label: 'Projects'
    label_singular: 'Project'
    folder: '_content/projects'
    create: true
    delete: false
    preview_path: 'portfolio/{{slug}}'
    fields:
      - name: 'title'
        label: 'Name'
        widget: 'string'
      - name: 'published'
        label: 'Published'
        widget: 'boolean'
        default: false
      - name: 'date'
        label: 'Date'
        widget: 'datetime'
        format: 'YYYY-MM-DD-HH-mm'
        date_format: 'dddd, MMMM D, YYYY'
        time_format: 'h:mm a'
      - name: 'types'
        label: 'Types'
        widget: 'relation'
        collection: 'project-types'
        multiple: true
        search_fields: ['title', 'slug']
        value_field: '{{slug}}'
        display_fields: ['title', 'slug']
      - name: 'windows'
        label: 'Windows'
        widget: 'relation'
        collection: 'windows'
        multiple: true
        search_fields: ['title', 'slug']
        value_field: '{{slug}}'
        display_fields: ['title', 'slug']
      - name: 'images'
        label: 'Images'
        widget: 'relation'
        collection: 'project-imges'
        multiple: true
        search_fields: ['title', 'slug']
        value_field: '{{slug}}'
        display_fields: ['title', 'slug']
      - name: 'excerpt'
        label: 'Excerpt'
        widget: 'text'
      - name: 'color'
        label: 'Color'
        widget: 'string'
      - name: 'thumbnail'
        label: 'Featured Image'
        widget: 'image'
        allow_multiple: false
        media_folder: '/public/images/projects/{{slug}}'
      - name: 'windows'
        label: 'Windows'
        widget: 'image'
        required: false
        media_folder: '/public/images/projects/{{slug}}'
        media_library:
          config:
            multiple: true
      - name: 'images'
        label: 'Images'
        widget: 'image'
        required: false
        media_folder: '/public/images/projects/{{slug}}'
      - name: 'body'
        label: 'Body'
        widget: 'markdown'
  - name: 'project-types'
    label: 'Project Types'
    label_singular: 'Project Type'
    folder: '_content/project-types'
    create: true
    delete: false
    preview_path: 'portfolio/type/{{slug}}'
    fields:
      - name: 'title'
        label: 'Name'
        widget: 'string'
      - name: 'body'
        label: 'Body'
        widget: 'markdown'
  - name: 'educations'
    label: 'Educations'
    label_singular: 'Education'
    folder: '_content/educations'
    create: true
    delete: false
    preview_path: '/'
    fields:
      - name: 'title'
        label: 'Name'
        widget: 'string'
      - name: 'college'
        label: 'College'
        widget: 'string'
      - name: 'start_year'
        label: 'Start Year'
        widget: 'number'
      - name: 'end_year'
        label: 'End Year'
        widget: 'number'
      - name: 'body'
        label: 'Body'
        widget: 'markdown'
  - name: 'experiences'
    label: 'Experiences'
    label_singular: 'Experience'
    folder: '_content/experiences'
    create: true
    delete: false
    preview_path: '/'
    fields:
      - name: 'title'
        label: 'Name'
        widget: 'string'
      - name: 'company'
        label: 'Company'
        widget: 'string'
      - name: 'start_year'
        label: 'Start Year'
        widget: 'number'
      - name: 'end_year'
        label: 'End Year'
        widget: 'number'
        required: false
      - name: 'body'
        label: 'Body'
        widget: 'markdown'
  - name: 'windows'
    label: 'Windows'
    label_singular: 'Window'
    folder: '_content/windows'
    create: true
    delete: false
    preview_path: '/'
    fields:
      - name: 'title'
        label: 'Name'
        widget: 'string'
      - name: 'image'
        label: 'Image'
        widget: 'image'
        media_folder: '/public/images/windows/{{slug}}'
      - name: 'body'
        label: 'Body'
        widget: 'markdown'
  - name: 'project-images'
    label: 'Project Images'
    label_singular: 'Project Image'
    folder: '_content/project-images'
    create: true
    delete: false
    preview_path: '/'
    fields:
      - name: 'title'
        label: 'Name'
        widget: 'string'
      - name: 'image'
        label: 'Image'
        widget: 'image'
        media_folder: '/public/images/project-images/{{slug}}'
      - name: 'body'
        label: 'Body'
        widget: 'markdown'

